#!/bin/bash

FILE_TO_WATCH="ash/__init__.py"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$CURRENT_BRANCH" == "main" ]]; then
    if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "$FILE_TO_WATCH"; then
        VERSION_NUMBER=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' "$FILE_TO_WATCH")

        if [[ -n "$VERSION_NUMBER" ]]; then
            git tag "$VERSION_NUMBER"
            echo "Tagged with version $VERSION_NUMBER"
        else
            echo "No version number found in $FILE_TO_WATCH"
        fi
    fi
fi
