#!/bin/bash

FILE_TO_WATCH="ash/__init__.py"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$CURRENT_BRANCH" == "main" ]]; then
    if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "$FILE_TO_WATCH"; then
        VERSION_NUMBER=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' "$FILE_TO_WATCH")

        LAST_TAG=$(git describe --tags --abbrev=0)
        CURRENT_COMMIT=$(git rev-parse HEAD)

        TAG_MESSAGE=$(git log $LAST_TAG..$CURRENT_COMMIT --pretty=format:"%s")

        if [[ -n "$VERSION_NUMBER" ]]; then
            git tag "$VERSION_NUMBER" -m "$TAG_MESSAGE"
            echo "Tagged with version $VERSION_NUMBER"
        else
            echo "No version number found in $FILE_TO_WATCH"
        fi
    fi
fi
